default:
  # 服务监听端口
  listen: 8081
  log_dir: /Users/caoyuan/log

# 数据库地址信息
mongo:
  host: localhost
  user: root
  password: root
  port: 27017
  database: prometheus
  mongocollection: new
  kafkacollection: old

kafka:
  topic: custom_HOST
  partition: 0
  host: 10.50.7.101
  port: 9092
